name: .NET

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Version
      id: version
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      
    - name: Show version
      run: echo Version ${{ steps.version.outputs.tag }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Pack
      run: dotnet pack --configuration Release --output packages /p:Version=${{ steps.version.outputs.tag }}
      
    - name: Publish
      run: dotnet nuget push packages/*.nupkg --source https://nuget.pkg.github.com/legato/index.json --api-key ${{ secrets.PAT }} --skip-duplicate
